name: Run Test Suite

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
        - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}--${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/long_lived/')) && github.sha || '' }}
  cancel-in-progress: true

jobs:
  build:
    name: All tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      max-parallel: 4

    env:
      CHIK_ROOT: ${{ github.workspace }}/.chik/mainnet
      BLOCKS_AND_PLOTS_VERSION: 0.29.0

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Cache test blocks and plots
      uses: actions/cache@v3
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MIN: 1
      id: test-blocks-plots
      with:
        path: |
          ${{ github.workspace }}/.chik/blocks
          ${{ github.workspace }}/.chik/test-plots
        key: ${{ env.BLOCKS_AND_PLOTS_VERSION }}

    - name: Checkout test blocks and plots
      if: steps.test-blocks-plots.outputs.cache-hit != 'true'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release download -R Chik-Network/test-cache ${{ env.BLOCKS_AND_PLOTS_VERSION }} --archive=tar.gz -O - | tar xzf -
        mkdir "${GITHUB_WORKSPACE}/.chik"
        mv "${GITHUB_WORKSPACE}/test-cache-${{ env.BLOCKS_AND_PLOTS_VERSION }}/"* "${GITHUB_WORKSPACE}/.chik"
        find "${GITHUB_WORKSPACE}/.chik" -type f | xargs sed -i 's/\xE3\xB0\xC4\x42\x98\xFC\x1C\x14\x9A\xFB\xF4\xC8\x99\x6F\xB9\x24\x27\xAE\x41\xE4\x64\x9B\x93\x4C\xA4\x95\x99\x1B\x78\x52\xB8\x55/\x4B\x8F\x8F\x2F\x85\x2C\x0A\x89\xA0\xF9\x7A\x1B\xC9\x1F\x18\x06\xE1\xF2\xEF\xD4\x92\x4F\xC3\xA8\x2B\xEC\x9A\x7B\x31\xB6\x1F\x31/g'
        find "${GITHUB_WORKSPACE}/.chik" -type f | xargs sed -i 's/\xD2\x3D\xA1\x46\x95\xA1\x88\xAE\x57\x08\xDD\x15\x22\x63\xC4\xDB\x88\x3E\xB2\x7E\xDE\xB9\x36\x17\x8D\x4D\x98\x8B\x8F\x3C\xE5\xFC/\x09\xB2\x39\x5C\x02\xBF\x08\x90\x6A\x78\xE3\xBD\x10\xF4\x84\x9E\x18\x2C\x2B\x05\x08\x64\x19\xEB\xB9\x0A\xC9\x4B\xCD\x9B\x00\x94/g'
        find "${GITHUB_WORKSPACE}/.chik" -type f | xargs sed -i 's/\x3D\x87\x65\xD3\xA5\x97\xEC\x1D\x99\x66\x3F\x6C\x98\x16\xD9\x15\xB9\xF6\x86\x13\xAC\x94\x00\x98\x84\xC4\xAD\xDA\xEF\xCC\xE6\xAF/\x68\xE9\x83\x3C\x8E\xA4\xFE\x2F\x22\x2B\xF3\x6E\xA6\xFF\x22\x36\xCC\xC2\x09\xED\xA5\x0B\x56\xED\x84\x09\x1D\x75\xD3\xF3\xC4\xD5/g'

    - name: Test code with pytest
      run: |
        python3 -m venv venv
        . ./venv/bin/activate
        pip install .[dev]
        ./venv/bin/pytest tests/ -s -v --durations 0
